name: infra

services:
  # --------------------------------------------------------
  # 1. PROXY REVERSO (Nginx)
  # --------------------------------------------------------
  reverse-proxy:
    image: nginx:1.25-alpine
    container_name: proxy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Tus server blocks (donde defines los dominios)
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # Configuración global
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      # Certificados SSL
      - ./ssl:/etc/nginx/ssl:ro
      # Challenge para Certbot
      - ./certbot:/var/www/certbot:ro
    networks:
      - unas-network
    restart: unless-stopped
    depends_on:
      - sistema-web
      - pma

  # --------------------------------------------------------
  # 2. SISTEMA WEB (Tu aplicación)
  # --------------------------------------------------------
  sistema-web:
    build: ./sistema-web
    container_name: sistema-web
    restart: always
    volumes:
      - ./sistema-web:/var/www/html
    networks:
      - unas-network

  # --------------------------------------------------------
  # 3. BASE DE DATOS (MySQL)
  # --------------------------------------------------------
  db:
    image: mysql:5.7
    container_name: sistema-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - unas-network

  # --------------------------------------------------------
  # 4. PHPMYADMIN (Gestor BD)
  # --------------------------------------------------------
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: sistema-pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 64M
    networks:
      - unas-network
    depends_on:
      - db

  # --------------------------------------------------------
  # 5. FTP (Vsftpd)
  # --------------------------------------------------------
  ftp:
    image: fauria/vsftpd
    container_name: sistema-ftp
    restart: always
    environment:
      FTP_USER: alumno
      FTP_PASS: 1234

      PASV_ADDRESS: 172.16.24.137
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      # Montamos la carpeta del sistema web para subir cambios directo ahí
      - ./sistema-web:/home/vsftpd/alumno
    networks:
      - unas-network

networks:
  unas-network:
    driver: bridge
    name: unas-network